#
# SPDX-FileCopyrightText: Copyright (c) 2014-2026, Thindeck.com
# SPDX-License-Identifier: MIT

FROM ubuntu:14.04
MAINTAINER Yegor Bugayenko <yegor256@gmail.com>
LABEL Description="Ruby Docker image" Vendor="Thindeck.com" Version="1.0"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y ruby
RUN apt-get update
