assets:
  settings.xml: "yegor256/home#assets/thindeck/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"
  s3cfg: "yegor256/home#assets/s3cfg"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

install:
  - "sudo apt-get install -y openjdk-6-jre"
  - "wget --retry-connrefused http://yar.fruct.org/attachments/download/362/plantuml_7707-1_all.deb"
  - "sudo dpkg -i plantuml_7707-1_all.deb"
  - "wget --retry-connrefused https://oss.sonatype.org/content/repositories/releases/net/sourceforge/plantuml/plantuml/8000/plantuml-8000.jar"
  - "mv plantuml-8000.jar /usr/share/plantuml/plantuml.jar"
  - "gem install pdd"

deploy:
  script:
    - "sudo bundle install"
    - "mvn clean test install site-deploy -Pgh-pages -Psite -Pqulice --errors --settings ../settings.xml"
    - "mvn clean"
    - "pdd --source=$(pwd) --verbose --file=thindeck.xml"
    - "s3cmd --no-progress put thindeck.xml --config=../s3cfg s3://pdd.teamed.io/thindeck.xml"

merge:
  script:
    - "sudo bundle install"
    - "mvn clean install site -Pqulice -Psite --errors --settings ../settings.xml"
    - "mvn clean"
    - "pdd --source=$(pwd) --verbose --file=/dev/null"

release:
  script:
    - "mvn versions:set \"-DnewVersion=${tag}\""
    - "git commit -am \"${tag}\""
    - "mvn clean deploy -Pqulice -Psonatype -Pthindeck --errors --settings ../settings.xml"
