language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install:
  - sudo apt-get update -y
  - sudo apt-get install -y phantomjs
  - git clone --depth=1 https://github.com/n1k0/casperjs.git /tmp/casperjs
  - export PATH=$PATH:/tmp/casperjs/bin
script:
  - mvn clean install -Pqulice --batch-mode --errors
